# Generated by Django 4.2.13 on 2024-06-20 05:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mypetapp', '0003_payment_orderdetail'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pet',
            managers=[
                ('cpetobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
